displayName=ToB Recruitment Helper
author=Pirrkatt
description=Highlights ToB applicants and provides useful information.
tags=tob,notice,board,apply,highlight,team,party,gear,theatre,of,blood,inspect,chat
version=
plugins=com.tobrecruithelper.TobRecruitHelpPlugin
build=standard